---
- name: Gather facts
  setup:

- name: Ensure localhost in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.0.1.*"
    line: "127.0.0.1 localhost"
    state: present
  become: True

- name: Generate /etc/hosts for all of the nodes
  blockinfile:
    dest: /etc/hosts
    marker: "# {mark} ANSIBLE GENERATED HOSTS"
    block: |
        {% for host in groups['baremetal'] %}
        {% set api_interface = hostvars[host]['api_interface'] %}
        {{ hostvars[host]['ansible_' + api_interface]['ipv4']['address'] }} {{ hostvars[host]['ansible_hostname'] }}
        {% endfor %}
  become: True

- name: Install dependent packages for kubernetes nodes
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ common_dependent_packages }}"
  when:
    - inventory_hostname in groups['kubernetes']

# Try to stop and disable delegated service,
# let it go when not exists.
- name: Disable ufw service
  service:
    name: "{{ item }}"
    state: stopped
    enabled: False
  failed_when: false
  loop: "{{ services_to_disabled }}"
  when:
    - inventory_hostname in groups['baremetal']
