---
- name: Restart rpcbind service
  service:
    name: rpcbind
    state: restarted
    enabled: yes

- name: Restart "{{ item.name }}" service
  service:
    name: "{{ item.name }}"
    state: restarted
    enabled: yes
  loop:
    - {"name": nfs, "os": Centos}
    - {"name": nfs-kernel-server, "os": Ubuntu}
  when:
    - ansible_distribution == item.os
