---
- name: Restart rpcbind service
  service:
    name: rpcbind
    state: restarted
    enabled: yes

- name: Restart nfs service
  service:
    name: "{{ item.name }}"
    state: restarted
    enabled: yes
  loop:
    - {name: nfs, os: CentOS}
    - {name: nfs-kernel-server, os: Ubuntu}
    - {name: rpcbind, os: CentOS}
    - {name: rpcbind, os: Ubuntu}
  when:
    - ansible_distribution == "{{ item.os }}"
