---
- name: Restart rpcbind service
  service:
    name: rpcbind
    state: restarted
    enabled: yes

- name: Restart nfs service
  service:
    name: nfs-kernel-server.service
    state: restarted
    enabled: yes
