---
- name: Restart rpcbind service
  service:
    name: rpcbind
    state: restarted
    enabled: yes

- name: Restart nfs service
  service:
    name: nfs
    state: restarted
    enabled: yes
  when:
    - ansible_distribution == 'CentOS'

- name: Restart nfs-kernel-server service
  service:
    name: nfs-kernel-server
    state: restarted
    enabled: yes
  when:
    - ansible_distribution == 'Ubuntu'
