---
apiVersion: v1
kind: Service
metadata:
  name: sts-test
  labels:
    app: sts-test
spec:
  ports:
  - port: 18080
    name: sts-test
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-test
spec:
  serviceName: "sts-test"
  replicas: 2
  selector:
    matchLabels:
      app: sts-test
  template:
    metadata:
      labels:
        app: sts-test
    spec:
      containers:
      - name: sts-test
        image: nginx:latest
        ports:
        - containerPort: 80
          name: sts-test
        volumeMounts:
        - name: sts-test
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: sts-test
    spec:
      accessModes: [ "managed-nfs-storage" ]
      storageClassName: "sts-test"
      resources:
        requests:
          storage: 1Gi
