---
- hosts: kube-master
  tasks:
    - name: Ensure .kube folder exist
      file:
        path: ~/.kube
        state: directory

    - name: Copy admin.conf to into ~/.kube/
      shell: cp /etc/kubernetes/admin.conf  ~/.kube/config
      changed_when: false