---
- hosts: kube-master
  tasks:
    - name: Ensure .kube folder exist
      file:
        path: ~/.kube
        state: directory

    - name: Copy admin.conf to into ~/.kube/
      copy:
        src: /etc/kubernetes/admin.conf
        dest: ~/.kube/config
        remote_src: yes
        mode: '0600'
